### ISSUE TITLE
Include field alias in field CSS class?

### ISSUE THREAD

**Issue by somoreingold** [rhythmagency/formulate#100]
Hello!

Great plugin--it helped me solve so many issues. I do have a question though:

In the formulateField directive, your template just outputs the fieldtype for the CSS class. This is fine for some general CSS styling. But for more targeted CSS styling, How about also outputting the field alias too? so instead of just

`class="formulate__field--text"`

It could be something like:

`class="formulate__field--text  formulate__field_alias--first-name"`

...for a "First Name" text field.

I'm aware there's already a specific field-id attribute outputted, but using that string is not very clean or dependable.

Thanks!

**Comment by Nicholas-Westby** [comment]
Forum thread for reference: https://our.umbraco.org/projects/backoffice-extensions/formulate/formulate-questions/85732-include-field-alias-in-field-css-class

**Comment by somoreingold** [comment]
Workaround:
`
String.prototype.kebabCase = String.prototype.kebabCase || function () {
        return _.kebabCase(this); // lodash
    };
var app = angular.module("app", ["formulate"]);

    _CMS_.formDecorator = function ($provide) {
        $provide.decorator('formulateFieldDirective', function ($delegate) {
            var directive = $delegate[0];
            directive.template = '<div ng-class="\'formulate__field--\' + fieldCtrl.fieldType + \' formulate__field-alias--\' + fieldCtrl.alias.kebabCase()"></div>';
            return $delegate;
        });
    }
    angular.module('formulate').config(['$provide', _CMS_.formDecorator]);
`

**Comment by Nicholas-Westby** [comment]
Think I'll work on this now.

**Comment by Nicholas-Westby** [comment]
This has been implemented. Here's an example of the classes that will appear on a text field with an alias of "firstName":

* formulate__field
* formulate__field--text
* formulate__field-alias--first-name

It will be included in the next release of Formulate.
