### ISSUE TITLE
Text Constants not appearing on layout

### ISSUE THREAD

**Issue by cbikhazi** [rhythmagency/formulate#101]
Hi,

I am trying to add text to my form but the text constants are not appearing on the layout even though ive added them to my form? Therefore they will never appear on my form?

Thanks

C

**Comment by Nicholas-Westby** [comment]
Hello,

You can find a description of the text constant field here: https://github.com/rhythmagency/formulate/blob/f5a8e360aeb08b772c9dc20d8e717a3962b6e01e/src/formulate.app/Forms/Fields/TextConstant/TextConstantField.cs#L16

> A text constant field is useful, for example, when you need to store a bit of text in a field so that it can be sent as a parameter to a web API, but you otherwise don't need the field to be output to the page when the form is rendered.

In essence, a text constant field exists and is intended to exist only on the server side. It should never be displayed on the frontend of a website.

If you are after some sort of read only field, please submit a feature request. Also, you can implement one yourself if you like. You can read about that here: http://www.formulate.rocks/articles/custom-field-types

Alternatively, you can use the rich text field, which is already a read only field (used to display rich text).
