### ISSUE TITLE
reCAPTCHA field doesn't check if the script is already loaded.

### ISSUE THREAD

**Issue by LeaTark** [rhythmagency/formulate#104]
The reCAPTCHA field isn't displayed if the script has already been included by another form on the same page.

**Comment by Nicholas-Westby** [comment]
Thanks for the heads up. Based on this: https://github.com/VividCortex/angular-recaptcha/issues/166

And based on some info on the README for `angular-recaptcha`, it seems like I either need to specify a `widgetId` or `ng-model` in order for multiple recaptchas to work on the same page.

I won't be able to address this for a few weeks, but if you want to submit a pull request here's the code you'll want to start with: https://github.com/rhythmagency/formulate/blob/f5a8e360aeb08b772c9dc20d8e717a3962b6e01e/src/formulate.app/JavaScript/FormTemplates/responsive.bootstrap.angular/builtin-types.js#L248

**Comment by Nicholas-Westby** [comment]
I wasn't able to reproduce the issue. I created two forms on the same page, and they each had a captcha (one even had two):

![multiple-captchas](https://user-images.githubusercontent.com/5933222/31062965-a8372848-a6e3-11e7-8c10-37763cce0a78.png)

I'm closing this issue for now. Please open it again if you can still reproduce the issue and have additional information.

**Comment by LeaTark** [comment]
Formulate may not be the only form on a page with a recaptcha field.

Our other forms check for the existence of grecaptcha before loading https://www.google.com/recaptcha/api.js?render=explicit

In our tests, other forms with recaptcha work in any order and following formulate.  Formulate with recaptcha works only if it is first.

**Comment by Nicholas-Westby** [comment]
I doubt I'll be able to look into this anytime soon. If you want to submit a pull request, that would help greatly. If it helps, here's the commit where I originally implemented the recaptcha field type: https://github.com/rhythmagency/formulate/commit/2c6b8328e1aae1ebdbe690ee5469ef1003a0ba8e

Also, if you could share a repo that demonstrates the issue, that might help me to understand what is happening and may help bring about a solution sooner.

Here's the Angular component I use to inject recaptcha into the page: https://github.com/VividCortex/angular-recaptcha
