### ISSUE TITLE
Fiddling with the form, it now no longer renders

### ISSUE THREAD

**Issue by kgiszewski** [rhythmagency/formulate#106]
The form I messing with stopped working as I added removed\fiddled with the elements:

![image](https://user-images.githubusercontent.com/4653907/30880923-034a4f3c-a2d2-11e7-8aea-53c13b320a47.png)

Most specifically the 'submit' button isn't rendering:

![image](https://user-images.githubusercontent.com/4653907/30880945-172c2cb4-a2d2-11e7-81b4-b2fa29ccdf9e.png)

**Comment by Nicholas-Westby** [comment]
My guess would be that you added a field to the layout that you then deleted from the form and that now needs to be deleted from the layout. Not sure though. What's your layout look like?

**Comment by kgiszewski** [comment]
Bingo that was it. I updated the layout. Perhaps a "you can't delete me b/c i'm in a layout" warning or the layout gets altered automagically ;P

Thanks sir.

**Comment by Nicholas-Westby** [comment]
The challenge with that is that the layouts are extensible, so there may very well be a layout that functions in a drastically different way. For example, another layout might take a snapshot of fields so it works even with deleted fields. Maybe I could add some sort of "field removed from form" event to allow layouts to remove the field themselves, but I'll leave that for another issue if anybody has a strong interest in it. For now, the quick solution would probably be to skip over any deleted fields.
