### ISSUE TITLE
How to add node properties to subject or form body?

### ISSUE THREAD

**Issue by afabri73** [rhythmagency/formulate#108]
Hi,
I need to use the same form for different page.
When I send email, I must customize the subject (or email body) specifying some node property (for example: Node name and Parent name)

I must configure it in the handler or I need to create hidden fields with node property as value?
Anyway...how could I do it?

Thanks for support

**Comment by Nicholas-Westby** [comment]
This is possible. However, this question is better suited to the forum: https://our.umbraco.org/projects/backoffice-extensions/formulate/formulate-questions/

The issue tracker should be restricted to bugs and feature requests.

Once you post it on the forum, I or another user will post an answer.
