### ISSUE TITLE
Umbraco 7.8.0 Doesn't finish Install after "Thanks for installing Formulate!" screen

### ISSUE THREAD

**Issue by garyhammett** [rhythmagency/formulate#110]
I'm in the development phase of creating a new website. 

I have installed Umbraco on a fresh project in a new solution, the site runs and functions through local IIS.
I've used the "Developer > Packages" approach to install formulate.

I see the following screen.
![image](https://user-images.githubusercontent.com/12448034/33346248-efc4a3c2-d486-11e7-80b8-6bac89c1f3f5.png)

If i wait 30 seconds, nothing new happens.

Log out, Login.

I see no formulate icon on the left and I can see the package is installed from Developer > Packages > Installed.

Any suggestions?

Should I try the Nuget package route instead?

**Comment by Nicholas-Westby** [comment]
My guess is you have some permission issues. Formulate attempts to modify a few files (e.g., web.config, trees.config, applications.config, and so on) after the initial install. It also waits a bit (30 seconds or so) after the initial install to work around some Umbraco quirks. If the website doesn't have permission to modify all of those files, you may run into some issues. So my first suggestion would be to ensure your permissions are all correct.

Also, I would in general recommend NuGet for any Umbraco package that provides a NuGet package. It's just cleaner for upgrades and makes maintenance a bit easier.

That being said, I haven't tested Umbraco 7.8 (it's still in beta), so there could very well be some breaking change that may be preventing Formulate from installing.

BTW, after you install Formulate, also be sure to go to the "Users" section and give yourself permission to the Formulate section.

**Comment by garyhammett** [comment]
Hi @Nicholas-Westby, looks like the permission bit did it for me.

I'm new to umbraco and how it all works. It's still relatively new. Thanks for the prompt response. I will test it out and report any bugs that may occur with 7.8

So far so good for installation:

![image](https://user-images.githubusercontent.com/12448034/33347045-7b25e758-d489-11e7-8625-1a7c56732e51.png)
