### ISSUE TITLE
Any update about Umbraco 7.9 version

### ISSUE THREAD

**Issue by sheryever** [rhythmagency/formulate#112]
Are you people trying to catch Umbraco 7.9 version?

**Comment by Nicholas-Westby** [comment]
Hello Abu Ali Muhammad Sharjeel,

I'm not sure which version you're referring to. The current version of Umbraco is 7.7.9, and the upcoming version is 7.8. Nowhere has there been any mention of Umbraco 7.9.

Regardless, I don't understand your question. What do you mean by "catch Umbraco 7.9"? Are you encountering some issue with some version of Umbraco with regard to Formulate?

**Comment by sheryever** [comment]
Sorry @Nicholas-Westby  I am talking about 7.7.9.

This is my first time to implement Formulate and i am demonstrating umbraco first time in my company, and if they liked we will start from the latest version of Umbraco.

**Comment by Nicholas-Westby** [comment]
Gotcha. Are you seeing any particular issues with Formulate when used with Umbraco 7.7.9? I am not aware of any issues.

**Comment by Nicholas-Westby** [comment]
@sheryever, I'm glad you got it working.

FYI, the documentation at http://www.formulate.rocks/ is open source and is available at https://github.com/rhythmagency/formulate/tree/gh-pages. If you'd like to revise it, please submit a ticket and a pull request. Would love to have a new contributor 😃
