### ISSUE TITLE
Incorrect URL being returned

### ISSUE THREAD

**Issue by jaydcrowe1989** [rhythmagency/formulate#117]
I have just installed formulate in the most update to date version of umbraco and everything seems to be running fine. I can create a form but when I try to delete it I get a 404 error and it cannot find the deleteform.html

It is trying to locate the form at http://localhost/App_Plugins/formulate/menu-actions/deleteForm.html

The url should be http://localhost/{siteName}/App_Plugins/formulate/menu-actions/deleteForm.html

Any help would be appreciated

**Comment by Nicholas-Westby** [comment]
Sounds like you have your site setup as a virtual directory or something of that sort so that it's not at the root of the domain.

Can you let me know how you have your site setup so that I can create a similar setup locally and reproduce the issue?

**Comment by jaydcrowe1989** [comment]
Thanks for getting back to me.

I just have the site set up locally on iis under the default site.

**Comment by Nicholas-Westby** [comment]
When you log into Umbraco, do you do so at site.com/umbraco or site.com/sitename/umbraco?

**Comment by Nicholas-Westby** [comment]
FYI, I just did a test on the latest Formulate and latest Umbraco and deleting a form worked fine. I definitely think it has to do with creating an Umbraco install that is not at the root of the domain, so if you could give me some additional information about your setup it would be really helpful.

**Comment by jaydcrowe1989** [comment]
I am running this all locally at the moment so when I log in it is
localhost/sitename/umbraco

**Comment by jaydcrowe1989** [comment]
Which is the best recommended way to install formulate? Is it best to download the zip and install that way or through nuget?

**Comment by Nicholas-Westby** [comment]
I typically install Formulate with NuGet. Makes upgrades really easy. And it's easier to manage the binaries in source control.

BTW, how did you set it up locally so that Umbraco is under localhost/sitename/umbraco rather than localhost/umbraco? Once I know how you've set that up, I can begin testing it myself.

**Comment by jaydcrowe1989** [comment]
Now resolved. The only issue I have now is that I want the user to be able to select a form as part of the grid layout. Am I best creating a macro partial which then the user can select the relevant form and show it wherever in the grid layout?

**Comment by Nicholas-Westby** [comment]
I'm glad to hear your issue has been resolved. I'll close out this ticket now.

For general questions, such as the one about working in the grid, the best place to ask those is in the forum: https://our.umbraco.org/projects/backoffice-extensions/formulate/formulate-questions/
