### ISSUE TITLE
Radio Button List

### ISSUE THREAD

**Issue by jaydcrowe1989** [rhythmagency/formulate#121]
Hi,

When I create a new radio button list and add a Data Value list I want to set the orientation as Horizontal. I set the Orientation to be horizontal but it shows as vertical on my page?

Thanks,
Jay

**Comment by Nicholas-Westby** [comment]
IIRC, setting the orientation just tacks on a different CSS class, which then gives you the ability to style the field with that orientation. It is up to you to create those CSS styles.
