### ISSUE TITLE
Character Encoding Error

### ISSUE THREAD

**Issue by ahmetturknet** [rhythmagency/formulate#141]
Hello,

I use Umbraco v7.12.2/Formulate v2.4.3. I setup formulate forms, handlers, layouts, configs, etc. I can send email but received emails gives character error in MacOS. Windows works correctly.

I think it is character encoding error. I would be very glad if you help.

Thanks in advance, Ahmet

![Windows](https://user-images.githubusercontent.com/33736666/56947420-d73c4200-6b35-11e9-8bd5-9eb88d64cfb1.png)
Windows

![MacOS](https://user-images.githubusercontent.com/33736666/56947421-d7d4d880-6b35-11e9-8109-bd57bad43b85.png)
MacOS

Then I tried to add email headers in email.config file but didn't work again :(
![emailconfig](https://user-images.githubusercontent.com/33736666/56947561-38641580-6b36-11e9-8fd6-cd74f544f53b.png)

**Comment by Nicholas-Westby** [comment]
This should be fixed in the latest version of Formulate (2.4.5). At least, I've set the body encoding to UTF8. Give it a shot and let me know how it works out for you.

**Comment by ahmetturknet** [comment]
Hi Nicholas,

Sorry, I'm late. I installed Formulate 2.4.5 version and I also tried on a couple of MacOS computers.  Unfortunately, it is not still working. If you tried correctly please send me your project.  I am open your all suggestions. 

Thanks for everything,
Ahmet

**Comment by Nicholas-Westby** [comment]
Can you attach a text file with some special characters that I can test with?

In the mean time, feel free to setup Formulate on your local computer to see if you can get a fix working. Or just try with a new project in Visual Studio using SmtpClient and MailMessage.

If you can get it working with some sample code, you can send it my way and I'll integrate it into Formulate.

**Comment by ahmetturknet** [comment]
Hi Nicholas, 

I tried on a new project which I attached a link and also attached a text file. 

[Forumalate Smample Project](https://github.com/ahmetturknet/WebApplication7)
[text.txt](https://github.com/rhythmagency/formulate/files/3165299/text.txt)

Thank you for your time,
Ahmet

**Comment by Nicholas-Westby** [comment]
I don't think I'll be able to test properly on my end. When I download that text file, this is what it looks like on Windows and macOS.

# Windows

![windows](https://user-images.githubusercontent.com/5933222/57539139-0eb1a800-7307-11e9-8fa6-94cbac71284c.png)

# macOS

![mac](https://user-images.githubusercontent.com/5933222/57539148-15401f80-7307-11e9-9029-804de0595ae7.png)

So on my computer, the characters already appear corrupted before I send them in an email.

If you want to create some code that may fix the issue, I can integrate it into Formulate and create a release for you to try. Below is some code to help you get started.

Constructing a MailMessage: https://github.com/rhythmagency/formulate/blob/b878a478af0aa9a255ab8d786586dd5e547a4a37/src/formulate.app/Forms/Handlers/Email/EmailHandler.cs#L238-L241

Add the message: https://github.com/rhythmagency/formulate/blob/b878a478af0aa9a255ab8d786586dd5e547a4a37/src/formulate.app/Forms/Handlers/Email/EmailHandler.cs#L341-L353

Send the email with SmtpClient: https://github.com/rhythmagency/formulate/blob/b878a478af0aa9a255ab8d786586dd5e547a4a37/src/formulate.app/Forms/Handlers/Email/EmailHandler.cs#L376-L379
