### ISSUE TITLE
Get Form by Form Id

### ISSUE THREAD

**Issue by jaydcrowe1989** [rhythmagency/formulate#144]
Is there a way to get a form by the form id? I've tried all sorts of ways but it doesn't work? I have a macro parameter created from the Form Picker. This works and I get the Form Id back but then I need to get a ConfiguredFormInfo

**Comment by Nicholas-Westby** [comment]
Closing this so this discussion can happen in one place: https://our.umbraco.com/forum/templates-partial-views-and-macros/97375-formulate-get-configuredforminfo-by-form-id
