### ISSUE TITLE
Pure CSHTML template

### ISSUE THREAD

**Issue by ruant** [rhythmagency/formulate#145]
Does anyone have a pure CSHTML version of a template?
The Angular/javascript stuff is pure mess.  
Perhaps somone has made a SurfaceController to make submitting data simpler too?

**Comment by Nicholas-Westby** [comment]
Hello,

The best place to have discussions or get questions answered is the forum: https://our.umbraco.com/packages/backoffice-extensions/formulate/formulate-questions/

You are welcome to contribute a pull request if you would like to add features to Formulate. Please be sure to submit an issue that outlines the issues, your proposed solution, and your strategy to implement that solution before investing too much time coding one (this is to ensure you do not waste your time).

Also, please be sure to create one issue per request.

**Comment by ruant** [comment]
Got a working solution.
Had to change a few minor things in the SurfaceController, that's basically it.
For clientside validation it does uses jquery and unobtrusive validation.

Haven't ported over all the fields yet, just the ones I needed, but the rest shouldn't be that hard to do.
And if the serverside validation fails, the values in the fields are lost. Might be someway to get around this too, but haven't looked into it that much since the client-side should stop it from submitting if anything isn't correct.

**Comment by Nicholas-Westby** [comment]
Sounds interesting; I'm glad to hear you found something that works for you. If you're planning to submit a pull request, some items should be addressed:

* Please avoid jQuery. It does not seem necessary.
* Some fields can only really be validated on the server side (e.g., reCaptcha, and some custom fields created by developers who customize Formulate).
* Sounds like you're doing a full-page postback on submit. You should be able to do an AJAX submit even though the form is rendering server side. This has multiple benefits, one of which is that it fixes the issue of losing field values.
* Please create a ticket that outlines the motivation for this and the technical details regarding the approach you've chosen. This will make it faster to validate and incorporate the pull request.

**Comment by ruant** [comment]
There isn't one line of javascript, just have to load jquery.unobtusive (and it's dependencies, jquery.validate and jquery) That is way simpler then the 4k+ lines of js currently being used IMHO.

Each field has it's own partial view, so it's easily customizable. Just razor syntax, no js.

Indeed, full postback, I'm looking into the issue with values disappearing, there has to be an super easy solution of this.
When you use "fixed" models this works fine, so probably just have to do some mapping from the "dynamic" model with the data we get back our from the SurfaceController and into the fields.

**Comment by Nicholas-Westby** [comment]
jQuery, jQuery.Unobtrusive, and jQuery.Validate combined are several times larger than the plain JavaScript template for Formulate (last I checked, 25KB minified, 8KB gzipped). They were just written by somebody else.

Please find an alternative to jQuery for the CSHTML template. Heck, you might even be able to get away with validating using HTML5 attributes `required` and `pattern`: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation

In which case you would truly have no JavaScript. This is supported on all major browsers:

* https://caniuse.com/#feat=form-validation
* https://caniuse.com/#feat=input-pattern
