### ISSUE TITLE
Any plans for Umbraco 8+?

### ISSUE THREAD

**Issue by biapar** [rhythmagency/formulate#150]
Any plans for Umbraco 8+?

**Comment by Nicholas-Westby** [comment]
Yes, version 3 is for Umbraco 8, but it's only currently available via NuGet: https://www.nuget.org/packages/Formulate/3.0.0

We've done a soft launch, as we want to handle some rough edges (e.g., I think there was some issue with validations). If you want to help smooth some of those rough edges with some pull requests, it would be appreciated.

**Comment by biapar** [comment]
Ok..I'll try it on a new small project on U8.
