### ISSUE TITLE
Any updates on supporting Umbraco 8?

### ISSUE THREAD

**Issue by halfer53** [rhythmagency/formulate#151]
I can see that the branch develop-umbraco-8 was updated from 2 months ago. I wonder if formulate will support Umbraco 8 eventually?

**Comment by Capellan29** [comment]
I'm also need this package working on v8

**Comment by jamiepollock** [comment]
Hi both, there is a nuget package for v3 (https://www.nuget.org/packages/Formulate/3.0.0). This is a soft launch. We’re not sure if there is an issue with this release regards field validation or not.

Sadly, we’ve not found the time to fully support this release.

If you do find any issues let us know. A PR would be appreciated.

- Jamie
