### ISSUE TITLE
Honour carriage returns in Message field for email handler. (Umbraco v7)

### ISSUE THREAD

**Issue by TFAstudio** [rhythmagency/formulate#152]
At present an Email Handler can include text populated in the Handler via the "Message" field. This plain text field meets many requirements to add text to any email initiated by a form submission. The multi-line text box form field can only be populated with plain text, but does save that text with carriage returns to allow some formatting.

Unfortunately when emails are dispatched by the handler, line breaks saved in this field are removed (and replaced with a space). Thus all formatting is lost.

Ensuring carriage returns in the Message field were honoured by the Email Handler would make this field very useful and bypass most requirements for HTML email.

Note: A potential workaround I tired, was to add a Rich Text field to the form itself, containing the desired text message, but leaving it out of the form layout. In the email handler I then included this field in my "Include Specific Fields" selection. This moment of genius was, however, wasted. Rich Text fields are overlooked by the Email Handler too, even when discretely specified - so the net effect was zero. This approach would be a nice way to add additional information in amongst the submitted form field values, as you get to decide the order per handler.

**Comment by TFAstudio** [comment]
We have corrected this, and built and tested.  I have tried several times to figure out the process for pull requests from your repository, it is all locked down so I cannot commit and push any changes, which is fair enough ,but how am I supposed to get a pull request so you can review and merge?  Could you please outline the process so this change can be merged in?

Thank you

**Comment by jamiepollock** [comment]
@TFAstudio thank you for your PR #153. We had a issue come up during testing after merging the PR which was the functionality implemented only works when "Append Fields" is checked in the emailHandler config. This means the behavior of the Message field is behaves unexpectedly when this second field is not checked.

Could you possibly submit a second PR to have this functionality to work when "Append Fields" is unchecked too?

**Comment by Nicholas-Westby** [comment]
This has been released as part of Formulate 2.4.7: https://github.com/rhythmagency/formulate/releases/tag/v2.4.7
