### ISSUE TITLE
Validation fails even when the field is not required, but the field has a type validation

### ISSUE THREAD

**Issue by JJCLane** [rhythmagency/formulate#160]
If you set validation on two fields, for example email and phone, but set neither of them to be required, the validation will fail server side if either of them are left blank. To me this seems like undesired behaviour? I would expect the validation to only apply when a value has been submitted for the field.

**Comment by Nicholas-Westby** [comment]
I don't follow exactly. 

Which type of validation are you setting? Is it the regular expression validation? If so, that might also validate empty values. To get around that, you can make the entire expression optional. For example, if you are validating an email like so:

```
^.+@.+$
```

You can instead use this regular expression:
```
^(.+@.+)?$
```

But I'm not sure if that's exactly what you are talking about.

**Comment by JJCLane** [comment]
Yeah we're currently just using the built in regex validations (email, phone, etc). That sounds like it could work, although I wonder if it could change the validation based on whether the field is required or not?

**Comment by Nicholas-Westby** [comment]
I can see situations where somebody might want to validate an empty field, so my thought is that it should remain as is.

FYI, there are not built-in email and phone validations. Regular expression validation is built in, but Formulate doesn't come with any specific regular expressions.

Closing this issue.

**Comment by JJCLane** [comment]
Ah ok my apologies. Just out of interest, what situation would you want to validate a non-required empty field?

**Comment by Nicholas-Westby** [comment]
For example, if you want a single error message in both empty and invalid and non-empty situations (e.g., "The specified email address is invalid.").

I could also see some more exotic field types where null/undefined/empty string are validated differently (e.g., if null means "this field was never touched" and empty string means "this field was touched, but the selection wasn't made").

**Comment by JJCLane** [comment]
Good points, always lots to think about when it comes to forms! Thanks for your help.
