### ISSUE TITLE
Disable Email Whitelist by Default

### ISSUE THREAD

**Issue by Nicholas-Westby** [rhythmagency/formulate#162]
See this issue: https://github.com/rhythmagency/formulate/issues/161

It seems the email whitelist is enabled by default (at least in the Umbraco 8 version). That is confusing. It should be disabled by default.

**Comment by Nicholas-Westby** [comment]
This is implemented and will be part of the next Formulate release.

**Comment by sumeshkp18** [comment]
Hi,
I also experienced the same issue. I was stuck for long time because of the issue. I hope the new release will come very very soon.

thanks

**Comment by Nicholas-Westby** [comment]
This is in the latest release of Formulate (version 3.2.1).
