### ISSUE TITLE
Issue rendering the form

### ISSUE THREAD

**Issue by andrcami** [rhythmagency/formulate#167]
Hi I followed the instructions for the simple JS implementation (without angular) and can trace my data is correct till @Html.Action("Render", "FormulateRendering", new { form = ((Umbraco.Web.PublishedModels.Home)Model).BottomForm }). 

I do not get any errors however the form is not rendering. any idea to why?

**Comment by Nicholas-Westby** [comment]
Hello. The best place to ask questions like this is on the forum: https://our.umbraco.com/packages/backoffice-extensions/formulate/formulate-questions/

Be sure your layout has the form and template selected, be sure you are inserting the JavaScript, view page source to be sure all the necessary markup is there, and view the Chrome console for any errors.

If you are still having issues, let's carry on with this conversation on the forum.
