### ISSUE TITLE
V3 equivalent for formulate.api.Rendering.GetFormViewModel?

### ISSUE THREAD

**Issue by ruant** [rhythmagency/formulate#168]
In v3 `formulate.api.Rendering.GetFormViewModel` doesn't exists anymore.
Is there a new method available that we should use?

**Comment by Nicholas-Westby** [comment]
The best place to ask questions like this would be the Umbraco forum.

In fact, this may already contain the answer you are looking for: https://our.umbraco.com/packages/backoffice-extensions/formulate/formulate-questions/98662-form-rendering-formulate-in-3plus

**Comment by ruant** [comment]
Cheers @Nicholas-Westby 

Perhaps the docs should be updated since it's not valid anymore: http://www.formulate.rocks/render-form
Or maybe just add a V2 and V3 section.
