### ISSUE TITLE
Not able to send and save information in Umbraco V8.5.3

### ISSUE THREAD

**Issue by harshwardhandangra** [rhythmagency/formulate#169]
Hi Team,

I had configured the formulate plugin but not able to send and save information into backend.

Nothing happening in after click submit buttons.

Thanks

**Comment by Nicholas-Westby** [comment]
Sounds like a setup issue. Please outline more details in a forum post: https://our.umbraco.com/packages/backoffice-extensions/formulate/formulate-questions/

Things that will help if you note them in the forum post:

* Which instructions you are following to setup the form.
* If you've viewed the JavaScript console and the network tab for XHR requests.
* Any errors on the logs.
* What you mean by "nothing happens".
* The Formulate version.
* Screenshots.
* Anything else that you think may be of use.

**Comment by harshwardhandangra** [comment]
@Nicholas-Westby Please check the below screenshot. but its not sending data and after click submit no place where i can put custom message

http://prntscr.com/sejwey

https://prnt.sc/sel4os

http://prntscr.com/sel63r

**Comment by harshwardhandangra** [comment]
> Sounds like a setup issue. Please outline more details in a forum post: https://our.umbraco.com/packages/backoffice-extensions/formulate/formulate-questions/
> 
> Things that will help if you note them in the forum post:
> 
> * Which instructions you are following to setup the form.
> * If you've viewed the JavaScript console and the network tab for XHR requests.
> * Any errors on the logs.
> * What you mean by "nothing happens".
> * The Formulate version.
> * Screenshots.
> * Anything else that you think may be of use.

@Nicholas-Westby Please check the below screenshot. but its not sending data and after click submit no place where i can put custom message

http://prntscr.com/sejwey

https://prnt.sc/sel4os

http://prntscr.com/sel63r

**Comment by Nicholas-Westby** [comment]
GitHub isn't the place for this conversation. Please refer to my above message with the link to the forum. And please include more information when you write the forum post.
