### ISSUE TITLE
Cannot get Contact form to render - Umbraco 8.6.1 installation

### ISSUE THREAD

**Issue by ChrisWNY** [rhythmagency/formulate#171]
I've followed the step-by-step install guide and cannot get the form to render properly in Umbraco 8.6.1. I've added the HTML snippet to contact.shtml within the /Views directory, no dice. I've also made sure both custom scripts are present - custom-formulate-script.js within the /scripts directory, verified read & execute permissions are present. 

Here is the code I placed into the contact.cshtml page:

--------------------------------------------------------

    @* Wrap the form with this element so the custom JavaScript can find it. *@
    <div class="formulate-wrapper">

        @* Render the form. *@
        @Html.Action("Render", "FormulateRendering", new { form = Model.MyForm })

    </div>

    @* The JavaScript file for Formulate's plain JavaScript template. *@
    <script src="/App_Plugins/formulate/responsive.plain-javascript.min.js" async></script>

    @* This is your JavaScript that handles events dispatched by Formulate. *@
    <script src="/scripts/custom-formulate-script.js" async></script>
-------------------------------------------------------

The error I get is as follows:

--------------------------------------------------------

Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.

Compiler Error Message: CS1061: 'Contact' does not contain a definition for 'MyForm' and no accessible extension method 'MyForm' accepting a first argument of type 'Contact' could be found (are you missing a using directive or an assembly reference?)

Source Error:

Line 48: 		
Line 49: 		        @* Render the form. *@
Line 50: 		        @Html.Action("Render", "FormulateRendering", new { form = Model.MyForm })
Line 51: 		
Line 52: 		    </div>
------------------------------------------------------

I have no idea what the "pick form" is called - the instructions on the formulate.rocks website don't seem to be up-to-date to explain how to do this in the 8.6.1 version of Umbraco. I'm using v3.2.1 of Formulate. 

I've set up the Formulate form per the instructions and added a Form Picker data type. I've attached screenshots as well. Any help/input appreciated. Thanks!

![formulate2](https://user-images.githubusercontent.com/65196976/82558695-381d2a80-9b3c-11ea-925b-0b9274f14fc6.jpg)
![fomulate1](https://user-images.githubusercontent.com/65196976/82558698-394e5780-9b3c-11ea-8987-6ed501f376ab.jpg)

**Comment by Nicholas-Westby** [comment]
The first thing that seems off is that you're using the "Form Picker" property editor. That does not belong to Formulate (I would guess that belongs to Umbraco Forms). Here's what Formulate's property editor looks like:

![Formulate's Property Editor Configuration Screen](https://user-images.githubusercontent.com/5933222/82574523-20de3d00-9b3c-11ea-9d0c-81c67c1e055c.png)

I would also check to be sure that your "Contact" page has a "MyForm" property and that the "MyForm" property is using the appropriate data type and that models builder is correctly generating the model for that property.
