### ISSUE TITLE
Support for installation in Umbraco Version 8.0 , 8.6.x ^ 

### ISSUE THREAD

**Issue by stixoffire** [rhythmagency/formulate#174]
Sorry if this is the wrong location to ask this question.
Really appreciate the hard work people put in to help one another out .
I am wondering when the next version - hopefully will have support for Umbraco versions 8.0 and up ?

Thanks and Cheers..

**Comment by Nicholas-Westby** [comment]
Formulate 2.x supports Umbraco 7.x, and Formulate 3.x supports Umbraco 8.x. You can find the latest versions of each via NuGet.

**Comment by Nicholas-Westby** [comment]
Here is some more info: https://www.formulate.rocks/requirements

**Comment by stixoffire** [comment]
@Nicholas-Westby  One note as I was building - there is an Ambiguity in one of the calls
In Responsive.Bootstrap.Angular.cshtml Line No. 59

```
    var getFieldConfig = new Func<FieldDefinition, object>(x =>
    {
```
Reports Ambiguity of FieldDefinition with Examine.FieldDefinition .

I have changed the code to fully Qualified.
formulate.core.Types.FieldDefinition

 ```  
   var getFieldConfig = new Func<formulate.core.Types.FieldDefinition, object>(x =>
    {
```

**Comment by Nicholas-Westby** [comment]
@stixoffire I don't recommend the AngularJS template (which is why it's hidden by default from new Formulate installs).

If you'd like to discuss anything further, please post on the forum: https://our.umbraco.com/packages/backoffice-extensions/formulate/formulate-questions/
