### ISSUE TITLE
Adding an email handler throws an error on the front end

### ISSUE THREAD

**Issue by sinkypars1885** [rhythmagency/formulate#183]
This is due to when serialising the handler config string to the EmailConfiguration, it is expecting a string array, but it actually receives an object:

   public IEnumerable<string> Recipients { get; set; }

Pull request incoming.

**Comment by Nicholas-Westby** [comment]
Hello,

Thanks for reporting this issue an submitting a pull request for it. I'll validate the issue/fix and get a new version released ASAP.

**Comment by Nicholas-Westby** [comment]
I've verified the error. Here's the stack trace I get when attempting to submit a form that has a handler to send emails:

![Stack Trace](https://user-images.githubusercontent.com/5933222/101658225-a69ed880-39f9-11eb-982d-48e8deb92c66.png)

I'll merge in the pull request shortly.

**Comment by Nicholas-Westby** [comment]
Thanks again for the fix. This has been released in Formulate 3.4.1.
