### ISSUE TITLE
Unknown error. Please try again.

### ISSUE THREAD

**Issue by IceLynxs** [rhythmagency/formulate#185]
Install : no errors
Adding a Form: no errors
Adding Rendering: no errors

But when i test the Form i become an error:

Unknown error. Please try again.

![image](https://user-images.githubusercontent.com/75845125/101911404-9be27000-3bc0-11eb-8f1e-56e7224f50f0.png)

Backend Log:

Dec 11, 2020 2:42:46 PM | Error | VM4232074 | An error occurred while preparing one of the Formulate form handlers.
-- | -- | -- | --
ExceptionNewtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Guid' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly. To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'recipientFields[0].id', line 9, position 11.    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)    at formulate.app.Helpers.JsonHelper.Deserialize[T](String value) in D:\r\formulate\src\formulate.app\Helpers\JsonHelper.cs:line 56    at formulate.app.Forms.FormHandler.PrepareHandleForm(FormSubmissionContext context) in D:\r\formulate\src\formulate.app\Forms\FormHandler.cs:line 147    at formulate.api.Submissions.SubmitForm(Guid formId, IEnumerable`1 data, IEnumerable`1 files, IEnumerable`1 payload, SubmissionOptions options, FormRequestContext context) in D:\r\formulate\src\formulate.api\Submissions.cs:line 266

**Comment by Nicholas-Westby** [comment]
Thanks for the report.

It's hard to say from the stack trace, but my guess is we messed something up with the recent refactor in the email handler (it has some GUID parsing that it does).

Would you mind sending us a zipped version of your `~/App_Data/Formulate/Json/` folder? That'll help us troubleshoot better. You can either attach it here or send me a message with a link on my website: http://www.nicholaswestby.com/contact

Also, which version of Umbraco and Formulate are you using?

**Comment by IceLynxs** [comment]
Thanks for the fast answere!

I use:
Umbraco: 8.6.4
Formulate: 3.4.1 

[Json.zip](https://github.com/rhythmagency/formulate/files/5680071/Json.zip)

**Comment by Nicholas-Westby** [comment]
A fix has been included in Formulate 3.4.2. Thanks again for the report and the quick follow up.
