### ISSUE TITLE
RegEx Validations Always Fail

### ISSUE THREAD

**Issue by sinkypars1885** [rhythmagency/formulate#187]
Take the email address validation for example:

![image](https://user-images.githubusercontent.com/62436117/102192997-6c2eb300-3eb3-11eb-90bb-d0b01ce56740.png)

^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$

Any Regex I try for email will always return invalid.

**Comment by Nicholas-Westby** [comment]
Thanks for the report. I noticed this myself last night as well. Should have a fix later today.

The issue seems to be that the backend is passing null to the frontend instead of the actual pattern.

**Comment by Nicholas-Westby** [comment]
This has been fixed in Formulate 3.4.5.

**Comment by sinkypars1885** [comment]
Brilliant, thank you 👍
