### ISSUE TITLE
Form rendering on AngularJS >1.5.11

### ISSUE THREAD

**Issue by rgdagostino** [rhythmagency/formulate#190]
Good afternoon!
I had to update angularJS to version 1.6.9 for a specific security issue of a client (cross site scripting vulnerability...) and I realised that the angular template of formulate (umbraco7) does not work with angular>1.5.11.

The error I get in the file responsive.bootstrap.angular.js is the following:

TypeError: Cannot read property 'fields' of undefined
    at FormulateController (http://localhost:55276/App_Plugins/formulate/responsive.bootstrap.angular.js:837:19)

Any chance the plugin will be updated to support the latest angularJS, or at least aiming for 1.6.9?
Cheers,
Giampiero

**Comment by Nicholas-Westby** [comment]
Hello,

I'm not really investing much energy into the AngularJS template anymore now that the plain JavaScript template exists.

However, if you or somebody else would like to submit a pull request, I'd be happy to review it and create a new release incorporating your changes.

**Comment by Nicholas-Westby** [comment]
This has been open a year and is unlikely to be addressed, so closing the issue.
