### ISSUE TITLE
Formulate - View Submissions

### ISSUE THREAD

**Issue by justinaseeley** [rhythmagency/formulate#198]
When going to the form submission area on the backoffice, if there are more submissions than fit on the screen, they cannot be viewed, scrolling is disabled and using the mouse to select and drag trick doesn't work either. I've only been able to get all submissions by exporting to excel.

**Comment by Nicholas-Westby** [comment]
Thanks for the report. I remember seeing that and could swear I fixed it. Which version of Umbraco/Formulate are you using?

**Comment by justinaseeley** [comment]
Hi Nicholas... Latest Umbraco V8 (not yet 9) and The latest formulate (3.5.1) installed from nuget in visual studio.

**Comment by justinaseeley** [comment]
when I load the backoffice, I get this error in the browser console:

DevTools failed to load SourceMap: Could not parse content for https://localhost:44378/app_plugins/amplify/ng-pattern-restrict.min.js.map: Unexpected token ﻿ in JSON at position 0

I wonder if it is related

**Comment by Nicholas-Westby** [comment]
I was able to reproduce this. I'll work on a fix when I get a chance. In the mean time, here's a workaround:

```
.umb-editor {
    overflow: scroll;
}
```

Including that CSS in the back office allows the screen to scroll.

This probably impacts more areas of Umbraco, so probably isn't a good real fix, but may work as a workaround for now.

Thanks again for the report.

**Comment by justinaseeley** [comment]
Thank you very much! I'll implement this now and see if it works. This is
very helpful. If I see other areas where overflow is an issue, I'll know a
quick fix.

**Comment by TFAstudio** [comment]
I've seen this issue too.
BTW: You can use the TAB key to navigate down the locked screen.

**Comment by justinaseeley** [comment]
.umb-editor {
    overflow: scroll;
}

does work

**Comment by jamiepollock** [comment]
Hey folks, I have a alternate fix (https://github.com/rhythmagency/formulate/commit/ca302c05b499fd4f305b4919634dc6facf7595df) in place on the develop branch right now in. This moves the submission view from using `umb-tabs` to using the `umb-editor-view`. This is a slight departure from the current look and feel of Formulate so I'll let @Nicholas-Westby have the final say on whether it gets introduced.

Here is a screenshot of the new layout running on my local version.

![Screenshot 2021-05-14 095141](https://user-images.githubusercontent.com/5408006/118280435-34e02480-b49a-11eb-9a80-72bcf26ccf4d.png)

**Comment by jamiepollock** [comment]
I got approval from @Nicholas-Westby via Slack. Closing this issue as it is now resolved in https://github.com/rhythmagency/formulate/releases/tag/v3.5.2. Available via NuGet and Our Umbraco.
