### ISSUE TITLE
Issue loading formulate in Umbraco due to json files in CamelCase

### ISSUE THREAD

**Issue by ghDragn** [rhythmagency/formulate#200]
Found an issue in the formulate system where the files were being saved in camel case rather than pascal case and the formulate system would then throw 500 errors when attempting to load the files.

Updated code in 3 files to fix the issue. 
Line 72: FieldsJsonConverter
var strTypeId = jsonObject["TypeId"].Value<string>();
becomes 
var strTypeId = jsonObject.GetValue( "TypeId", StringComparison.OrdinalIgnoreCase ).Value<string>();

Line 72: HandlersJsonConverter
same as FieldsJsonConverter

StoredDataController
Lines 204 - 207
var strGuid = (field.FieldId as object)?.ToString();
var guid = GuidHelper.GetGuid(strGuid);
var value = (field.Value as object)?.ToString();
var fieldName = (field.FieldName as object).ToString();
Becomes
var strGuid = ((field.FieldId ?? field.fieldId) as object)?.ToString();
var guid = GuidHelper.GetGuid(strGuid);
var value = ((field.Value ?? field.value) as object)?.ToString();
var fieldName = ((field.FieldName ?? field.fieldName) as object).ToString();

**Comment by Nicholas-Westby** [comment]
Thanks for the report and the suggested fixes.

Which version of Formulate are you using? And do you have some steps to reproduce (e.g., create form, add field, refresh page)?

I'm wondering if perhaps an older version of Formulate had a bug with saving the incorrect case that no longer exists in the latest versions.

**Comment by ghDragn** [comment]
Right the version, I upgraded formulate to 2.6.0 and the umbraco version is 7.12.4

It's not so easy to replicate. 
the issue started after we implemented a code change that included exporting certain content to json files that we could use in our external apis, part of that change required the use of Camel Case Property name contract resolver. 
after this all json files being serialized from our system seem to have been using that contract resolved.

I implemented a fix in the global.asax as below:
Newtonsoft.Json.JsonConvert.DefaultSettings = () => new Newtonsoft.Json.JsonSerializerSettings
        {
            ContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver()
        };

and while that resolved the issue, it also slowed the formulate system down so that it would take usually between 3 and 5mins to load the formulate forms from the json files.

**Comment by Nicholas-Westby** [comment]
Gotcha. That sounds like an issue outside of the scope of Formulate that could cause untold number of problems with most any plugin, so I'll be closing this issue.

I imagine what somebody would want to do if they encountered a similar issue would be to fix the actual casing in the Formulate JSON files (rather than modifying Formulate to allow for various casings).
