### ISSUE TITLE
Umbraco 9?

### ISSUE THREAD

**Issue by ruant** [rhythmagency/formulate#211]
Not sure where else to ask the question, but is the v4/main branch a start on adding support for Umbraco 9+?

**Comment by Nicholas-Westby** [comment]
Indeed. We're working on it, slowly but surely as time permits. With Umbraco 10 on the near horizon, it is likely the first version will skip Umbraco 9 entirely and instead target Umbraco 10.

If anybody would like to contribute their time to move this forward faster, we would welcome the extra help.

**Comment by V414** [comment]
I would certainly like to see Formulate updated to Umbraco 9/10 - its the only third-party Umbraco package I use on my site, and when we do upgrade from Umbraco 8 it would be brilliant to keep using the same forms package!

**Comment by ruant** [comment]
Is there a overview of what the plan is for the v4 branch?
What I mean about that is how is the end product envisioned to look like?
What has been done? What is missing that the community can help with.

**Comment by Nicholas-Westby** [comment]
There is not. We have basically just been using the JSON from some forms and rebuilding the back office tree, fixing things as we find they're broken. I can chat with the team and see if there may be some reasonable way to provide a todo list of remaining items. The end product will look essentially the same as the current one (maybe a few minor deviations).

If there are capable community members who are willing to help, this issue would be a good place to mention your willingness to volunteer.

**Comment by Nicholas-Westby** [comment]
If anybody wants to contribute, the layout designer in v4 isn't built out yet:

<img width="960" alt="layout-stub" src="https://user-images.githubusercontent.com/5933222/180308114-77e8238c-5e79-4287-bc2d-33305a842ccd.png">

Anybody willing to take that on? Let me know so I can focus on other things.

**Comment by Nicholas-Westby** [comment]
I'll be working on the layout designer since nobody has expressed interest in working on it.

I'll also be closing this ticket as I haven't heard from anybody regarding contributing specific things (feel free to reach out again if you are interested). We're making good progress and if no interruptions occur we may have something to release soon.

**Comment by cvocvo** [comment]
> Indeed. We're working on it, slowly but surely as time permits. With Umbraco 10 on the near horizon, it is likely the first version will skip Umbraco 9 entirely and instead target Umbraco 10.
> 
> If anybody would like to contribute their time to move this forward faster, we would welcome the extra help.

@Nicholas-Westby (sorry to reply to a closed ticket)
Does formulate or formulate pro support Umbraco 10 now? I can't tell from the plugin page if 8.1+ includes v10: https://our.umbraco.com/packages/backoffice-extensions/formulate/

**Comment by Nicholas-Westby** [comment]
No, Formulate does not support Umbraco 10. I'm also not sure it will. Some people have expressed interest in assisting with the upgrade, but it seems like most interested parties have since lost interest. It may still happen, but without help it would probably be best for you to consider alternatives.

**Comment by TFAstudio** [comment]
We love Formulate and have shortlisted Pro licenses for a number of Umbraco v7 sites which will be making the jump to v10 this year. We've been forced to use Umbraco Forms for some v10 sites which have already launched and we're not happy with the performance.
I really hope some of the Umbraco Dev community can get behind this project! Formulate Rocks!
