### ISSUE TITLE
Does deleting a data handler also delete all the associated records?

### ISSUE THREAD

**Issue by TFAstudio** [rhythmagency/formulate#239]
Hey folks,

Using Umbraco v7 with Formulate and wondering about data handlers and data retention. I have been using a "Store Data" handler with a form for testing and have thousands of test records.

If I delete the Handler, will all that data be deleted from the database?

This seems like a very efficient and straightforward way to cleanse and reset form data, but I'd like to confirm what is happening behind the scenes. Is it really gone?

Thanks all!
AE

**Comment by Nicholas-Westby** [comment]
Nope, deleting the handler will not delete stored form submissions. Deleting the handler will just ensure further submissions are not stored.
