### ISSUE TITLE
Formulate in 7.3.4

### ISSUE THREAD

**Issue by rodes74** [rhythmagency/formulate#25]
Hi Nicholas,

I know the package is made for  umbraco 7.4. I've tested in 7.3.4. Installs fine, 
But after i add the "Formulate section" to the user, everytime i go the user section i lose session. This also is happening in Developer section "Packages Installed".

Another problem is that after install i have 3 Formulate Sections on umbraco backoffice.

The package will only be developed for 7.4 version?

Best regards,

**Comment by Nicholas-Westby** [comment]
The intention is that Formulate will only be developed for the latest versions of Umbraco for now (to speed up development until it is more feature rich). That means that Formulate will not necessarily work in older version of Umbraco.

However, the bug you describe sounds an awful lot like one I thought I fixed that was happening in Umbraco 7.4.1. That is, I noticed that when I installed Formulate, I'd see some things duplicated, such as the "Formulate" section on the left hand side of the screen. I found that the installer was running some operations multiple times, including those that modify configuration files. It concerns me that this still occurs.

Could you give me some more details? For example, are you using the Formulate 0.2.0 from here?: https://github.com/rhythmagency/formulate/releases/tag/v0.2.0

Here are a few more questions:
* Also, can you check if there are duplicate items for Formulate in your dashboard.config and your applications.config (and perhaps your trees.config)?
* And what do you mean exactly by you "lose session"? Are you being logged out when you go to the user section?
* Do you have .NET 4.5.2 in your web.config:

```
<compilation defaultLanguage="c#" debug="true" batch="false" targetFramework="4.5.2">
```

If you have any more information that think may be of use, please do add it. Thanks!

**Comment by Nicholas-Westby** [comment]
By the way, do you have any of these errors in your Umbraco error log?: "An unknown error occurred while attempting to asynchronously run the install actions for Formulate."

**Comment by Nicholas-Westby** [comment]
The good news is that I can reproduce the error on Umbraco 7.3.4 (and I apparently didn't need to change target framework from 4.5 to 4.5.2... it installed fine... sort of):

![triple](https://cloud.githubusercontent.com/assets/5933222/14435149/3e6b62d2-ffcb-11e5-8a38-799bbf25c4da.png)

I'll see if I can reproduce on Umbraco 7.4.1.

**Comment by Nicholas-Westby** [comment]
Well, darn, I can reproduce the duplicate sections on Umbraco 7.4.1. I'll look into it ASAP. Thanks for the report!

**Comment by Nicholas-Westby** [comment]
By the way, the workaround is fairly simple. Just delete the extra entries from the applications.config. They look like this:

```
<add alias="formulate" name="Formulate" icon="icon-formulate-clipboard" sortOrder="6" />
```

**Comment by rodes74** [comment]
Hi Nicholas,

Thanks for your fast report.

I downloaded the version from http://www.formulate.rocks/ 
I already deleted the extra entries from applications.config and changed the sortOrder to one not used.
In my web.config the target framework is 4.5
I'm being logged out when i  go to "Users" Section editing my user. This also occurs when i go the installed packages on developer section 

This is my tracelog
[UmbracoTraceLog.txt](https://github.com/rhythmagency/formulate/files/213524/UmbracoTraceLog.txt)

**Comment by Nicholas-Westby** [comment]
Thanks for the info. By the way, the workaround may require you to recycle your application pool after you change the applications.config file. I have a fix and am testing it now.

**Comment by Nicholas-Westby** [comment]
Give this new version a try: https://github.com/rhythmagency/formulate/releases/tag/v0.2.1

For anybody who had this issue, they'll have to delete the extra entries from the applications.config manually:

```
  <add alias="formulate" name="Formulate" icon="icon-formulate-clipboard" sortOrder="6"/>
  <add alias="formulate" name="Formulate" icon="icon-formulate-clipboard" sortOrder="6"/>
```

Thanks again for your report!
