### ISSUE TITLE
Formulate breaks other custom fonts icons

### ISSUE THREAD

**Issue by bjarnef** [rhythmagency/formulate#29]
It seems you package is breaking other custom font icons, e.g Font Awesome font package and my Material Design Icon Pack.

In this line you should prefix it with `icon-formulate-` instead.
https://github.com/rhythmagency/formulate/blob/master/src/formulate.app/App_Plugins/formulate/styles/formulate-icomoon.css#L14

An example:
https://github.com/bjarnef/Material-Design-Icon-Pack/blob/master/GMD.IconPack/css/material-design-iconic-font.css#L18-L19

The first "home" icon is from font awesome, the second Google Material and the third in core.
![image](https://cloud.githubusercontent.com/assets/2919859/14501054/dbf7ef5e-01a4-11e6-82f8-29098e2e4bfc.png)

but it also conflict with other icons, e.g. the three first icons is in font awesome icon package (but Formulate override the custom font):
![image](https://cloud.githubusercontent.com/assets/2919859/14501103/0ab908d2-01a5-11e6-8556-9495006de59d.png)

**Comment by Nicholas-Westby** [comment]
Thanks for the report!

I'll see if I can get a new release out today.

**Comment by Nicholas-Westby** [comment]
Thanks again for the detailed bug report! This is fixed in the latest version, 2.2.0: https://our.umbraco.org/projects/backoffice-extensions/formulate/
