### ISSUE TITLE
Correct Validation CSS Class

### ISSUE THREAD

**Issue by Nicholas-Westby** [rhythmagency/formulate#35]
Seems like validation classes are added based on the alias of the validation rather than the type of validation. For styling, it seems like it'd be more useful to have a CSS class based on the validation type. For example, I'd prefer to see a CSS class of "ng-invalid-regex" rather than "ng-invalid-email".

**Comment by savega** [comment]
Switching validation alias for validation id 7af5797aa1b156aed4d2c84b3f61dafad40bf03f. For time being, we won't have nice class names.

**Comment by Nicholas-Westby** [comment]
Thanks, @savega !
