### ISSUE TITLE
Localization of tree nodes etc.

### ISSUE THREAD

**Issue by bjarnef** [rhythmagency/formulate#42]
Ensure tree nodes, labels in views etc. are localizable.

**Comment by Nicholas-Westby** [comment]
Thanks for the suggestion. In fact, it is already on the roadmap (under "Translate Back Office"): http://www.formulate.rocks/roadmap :-)

**Comment by Nicholas-Westby** [comment]
Putting this here for later reference when I get around to implementing translations: https://our.umbraco.org/forum/developing-packages/76705-problems-with-localization-in-ng-view :-)

**Comment by Nicholas-Westby** [comment]
It's going to take a while, but I've started the process of localizing the UI: https://github.com/rhythmagency/formulate/commit/80f146efa703ca3e8588eb802074fadcd6decf0a

Let me know if you have any recommendations if I'm doing anything in a non-standard way.

Also, note to self, this link is useful: https://our.umbraco.org/Documentation/Extending/Language-Files/Language-Files-For-Packages/

**Comment by Nicholas-Westby** [comment]
Note to self: Since the `<localize>` directive doesn't seem to compile Angular markup in the translation, I'll probably have to create my own version that does that.

**Comment by Nicholas-Westby** [comment]
@bjarnef FYI, everything has been made localizable in Formulate (just released in v0.3.1). Would you be interested in adding some translations?

**Comment by bjarnef** [comment]
@Nicholas-Westby okay, I can take a look at the Danish translation.
Is there a reason for adding markup to the language files? .. I think it should be avoided when possible.

examples:
```
<key alias="Add Handler"><![CDATA[
  <h5>
      Add a Handler (<a href="" ng-click="cancel()">Cancel</a>)
   </h5>
 ]]></key>
```

I think it would be easier to have something like:
```
<h5>
   <localize key="formulate_addHandler">Add a Handler</localize>
   (<a href="" ng-click="cancel()"><localize key="general_cancel">Cancel</localize></a>)
</h5>
```

"general_cancel" is just reused from core language files.

and for e.g "Delete Folder"

```
<key alias="Delete Folder"><![CDATA[
  <div>
     Are you sure you want to delete the folder, "{{folderName}}", and all of its descendants?
  </div>
 ]]></key>
```

instead:
```
<div>{{deleteFolderConfirm}}</div>
```

```
$scope.deleteFolderConfirm = localizationService.localize("formulate_deleteFolderConfirm", folderName);
```

```
<key alias="deleteFolderConfirm">Are you sure you want to delete the folder, %0%, and all of its descendants?</key>
```

Personal I just don't like when adding markup incl. related event like `ng-click` on the element inside the localization files, since it is easier to break stuff if a part of the localization is missing. Furthermore I also think it is much cleaner when it is separated, so markup is when is belongs - in the view. I know Umbraco also include a bit markup in the core language files, but I think it should be avoided. Just my 2 cents.

**Comment by Nicholas-Westby** [comment]
Yeah, I included markup in some of the translations to keep things simple and in context.
