### ISSUE TITLE
error when you choose them remove form selected

### ISSUE THREAD

**Issue by iangerdes** [rhythmagency/formulate#44]
hi 

im building a site with loads of forms on it for different treatments so i have created a partial view file to include within the pages @{ Html.RenderPartial("umbformulate"); }.

which has the following code:

@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using formulate.app.Types
	
@{	

    // Get a view model for the picked form.
    var pickedForm = Model.Content.GetPropertyValue<ConfiguredFormInfo>("formPicker");
    var vm = formulate.api.Rendering.GetFormViewModel(pickedForm.FormId, pickedForm.LayoutId,
        pickedForm.TemplateId);
}

<div ng-controller="formWrapper">

        
        <div ng-if="status !== 'success'">
            <div class="container">
                @Html.Partial("~/Views/Partials/Formulate/RenderForm.cshtml", vm)
            </div>
        </div>

        
        <div ng-if="status === 'success'">
            Your request has been received!
        </div>

        
        <div ng-if="status === 'failure'">
            Unable to submit request. Please try again.
        </div>

    </div>
	

 I have a problem when I select a form page it renders fine (it has some style issues) but when I deselect  the form i get an error. 

Exception Details: formulate.core.Exceptions.ViewNotFoundException: The specified Formulate view could not be located on the file system.

Line 3:  @{
Line 4:      var viewPath = Model.TemplatePath;
Line 5:      FileUtility.ValidateView(viewPath);
Line 6:  }
Line 7:  @Html.Partial(viewPath, Model)

i have tried an if statement to see if that will fix it

			
@if (CurrentPage.HasValue("formPicker"))
    {	
	<text>@{ Html.RenderPartial("umbformulate"); }</text>
	}
	
but no luck. any ideas? im not a full on coder so any help would be great.

regards,

Ian

**Comment by Nicholas-Westby** [comment]
You probably just need to add a bit of null checking. Something like this:

```
if (pickedForm != null && pickedForm.FormId != null)
{
    @Html.Partial("~/Views/Partials/Formulate/RenderForm.cshtml", vm)
}
```

By the way, I would recommend that questions such as these go in the forum rather than in the issue tracker: https://our.umbraco.org/projects/backoffice-extensions/formulate/formulate-questions/

If you have any further questions (e.g., sounds like you might have one regarding styles), please post there and I'll be sure to get back to you :-)

P.S. When your site goes live, I'd love to see how you're using Formulate.

**Comment by iangerdes** [comment]
Cheers for that Nicholas I've been looking for a nice form plugin for umbraco for a while so really happy with it. Few additional functions like a copy would make it very useful and time saving.

Thanks once again
