### ISSUE TITLE
Save Submitted Data. How?

### ISSUE THREAD

**Issue by biapar** [rhythmagency/formulate#49]
Save Submitted Data. How?

**Comment by Nicholas-Westby** [comment]
That feature is not yet supported. However, you could implement it by creating a custom submission handler that stores data for a submission (that's how I eventually plan to implement it). You can follow the example of the existing email handler that sends an email when a submission happens: https://github.com/rhythmagency/formulate/blob/809d7b6f504929d294e5f852b4e9e3458fce93cc/src/formulate.app/Forms/Handlers/Email/EmailHandler.cs

**Comment by Nicholas-Westby** [comment]
This has been implemented. Closing issue.

**Comment by biapar** [comment]
Good! Here is https://github.com/rhythmagency/formulate/commit/379fb615c4fa179be80139c1c889dc4c7538c996
