### ISSUE TITLE
No data source actions?

### ISSUE THREAD

**Issue by bjarnef** [rhythmagency/formulate#53]
It seems there are no data source actions?

![image](https://cloud.githubusercontent.com/assets/2919859/17537346/2a6d3474-5e9c-11e6-82e6-2a4a9e6045bf.png)

**Comment by Nicholas-Westby** [comment]
Indeed. That is a feature I haven't gotten around to implementing yet. It's basically going to be a source you can use anywhere data is used (e.g., a database connection string, or SMTP settings).

I'll leave this issue open as a reminder to implement this at some point.

If you like, I can temporarily hide that tree node so it doesn't confuse anybody.

**Comment by robgha01** [comment]
@Nicholas-Westby yea i got confused by it xD i was thinking maybe  the installation did not install correctly.

**Comment by Nicholas-Westby** [comment]
Cool. I'll hide it in an upcoming Formulate release.

**Comment by Nicholas-Westby** [comment]
FYI, I just added a warning banner for now so people are aware that this feature isn't implemented yet:

![warning](https://cloud.githubusercontent.com/assets/5933222/18638918/ae1cf6b4-7e46-11e6-8e65-12319fa53d51.png)
