### ISSUE TITLE
How To Extend Formulate

### ISSUE THREAD

**Issue by MaxChong** [rhythmagency/formulate#56]
Hi,

I would like to extend formulate by downloaded the zip file provided. When i open the 'Formulate.sln' and build it using Visual Studio, it will throw errors. Any advises?

Kindly regards,
Max

**Comment by Nicholas-Westby** [comment]
Which of the build techniques are you using from here?: https://github.com/rhythmagency/formulate#building

Make sure to run `npm i` and `grunt`. And make sure you are using Visual Studio 2015. If that doesn't help, let me know further details about what errors in particular you are experiencing.

By the way, there are a lot of ways to extend Formulate without downloading the source code. If you post a message over here explaining what you are trying to do, perhaps I can assist: https://our.umbraco.org/projects/backoffice-extensions/formulate/formulate-questions/

**Comment by MaxChong** [comment]
Hi Nicholas,

Solved it after knew that there are some C sharp 6 syntax and require visual studio 2015 for it. 

Thanks for the prompt reply and Formulate looks great !
