### ISSUE TITLE
Update Action Icons

### ISSUE THREAD

**Issue by Nicholas-Westby** [rhythmagency/formulate#65]
Need to update the icons for the actions that appear when right clicking nodes in the Formulate section. For example, create form, add folder, delete, move. They all use the same folder icon right now.

See this other ticket for some discussion around the icons: https://github.com/rhythmagency/formulate/issues/52

**Comment by axiom12** [comment]
I have a couple questions:

Right now the label in the menus for Formulate there is an "Add Folder" action. I am updating this icon to use the icomoon folder-plus icon across all the menu nodes to differentiate it from the "Add" action for each specific type of node (Layout, Form, Data Value, etc). See the image below for the menu for the Forms node menu and resulting created folder item.

![image](https://cloud.githubusercontent.com/assets/1196759/19817939/b334055e-9d1b-11e6-87f2-8d0d4b6fcc9b.png)

When a folder is created there is a different icon depending on which section you create the folder in.

![image](https://cloud.githubusercontent.com/assets/1196759/19817875/7a477118-9d1b-11e6-8061-2c971735dff7.png)


1. Should I leave the updated "Add Folder" icon as the only change?

2. Should I make the created folder icons consistent using the default folder icon?

3. Should I change the label on each folder node to more clearly reflect each particualr section and to make it a generic group? ("Add Form Group", "Add Layout Group", etc.)? This might clarify things with the icon being different by section. Even though they're really just container objects, if we aren't making something that looks like a folder, when the "Add Folder" action is clicked there might be some confusion.

**Comment by Nicholas-Westby** [comment]
I would suggest that we should keep it simple and go with your first option of showing the same icon for all "Add Folder" actions, and that we should not change the action text per tree (i.e., it should remain as is).

**Comment by Nicholas-Westby** [comment]
By the way, I have been reconsidering the folder icons I currently have that differ per tree section. I may at some point decide to unify them to a single icon, but that's something that I need to separately consider (i.e., let's not worry about it just yet, but just wanted you to have that bit of background).

Given enough time (not a luxury I currently have), I think I'd create custom icons that all look very similar, but that slightly differ depending on the tree (e.g., they may all have a folder-like icon, but an inset smaller icon that represents the section).

**Comment by axiom12** [comment]
ok I'll leave the different icons as is. I'm sorry about all the questions. I just don't want to do something that doesn't fit with the vision you have for the UI.

**Comment by Nicholas-Westby** [comment]
I very much appreciate the confirmation! Question away anytime.

**Comment by Nicholas-Westby** [comment]
This has been completed. Thanks for the ideas and involvement, @axiom12 !
