### ISSUE TITLE
Sort Fields in Emails & Submission List

### ISSUE THREAD

**Issue by Nicholas-Westby** [rhythmagency/formulate#68]
Right now, it seems like fields are listed in the order data is entered (e.g., if somebody fills in their last name before the fill in the first name, that is the order the fields will be displayed in for each handler).

Would be better to list the fields in the order indicated by the field list for the form.

**Comment by MuirisOG** [comment]
This is especially important in a case, for example, where you are asking users to fill in a change of address form. If they fill in the fields in a random order and it is emailed in this order, you will end up with new address fields mixed up with the old address fields. (Appropriately named fields help in this instance).

**Comment by Nicholas-Westby** [comment]
I'll prioritize this so it gets done soon (I'm thinking in the next few days).

**Comment by Nicholas-Westby** [comment]
This has been implemented in these commits:

* https://github.com/rhythmagency/formulate/commit/dce8771cd6a12cf8039cee506994856ffc6089bd
* https://github.com/rhythmagency/formulate/commit/8d6d1753f5baed4738fff4e9afcbcbbb947f36a8

I'll test it and include it with the next release of Formulate. Not sure when that will be, but probably in the next couple weeks.
