### ISSUE TITLE
How to review a Form Fields or Handler?

### ISSUE THREAD

**Issue by biapar** [rhythmagency/formulate#77]
How to review a Form Fields or Handler after submit them in the editor? It's not possible to change anything.

![image](https://cloud.githubusercontent.com/assets/661517/22367216/acf3fc10-e480-11e6-96f7-514a630d6201.png)

**Comment by Nicholas-Westby** [comment]
Click the plus sign to expand the item.

**Comment by biapar** [comment]
Yes, I find it, but there is any simbols or mouse icon or similar that suggest that it's a link or so. The mouse pointer remains an arrow.

Saluti
ing. Biagio Paruolo

**Comment by Nicholas-Westby** [comment]
Thanks for the suggestion. I created an issue so I don't forget to do that: https://github.com/rhythmagency/formulate/issues/80
