### ISSUE TITLE
How to retrieve submited data?

### ISSUE THREAD

**Issue by biapar** [rhythmagency/formulate#79]
How to retrieve submited data ( for example to list in a backed page or secured area )?

**Comment by Nicholas-Westby** [comment]
Not sure exactly what you mean. Are you talking about the built-in functionality to do so, or programmatically accessing stored submissions so you can build your own back office dashboard?

The release notes here indicate how to store and view form submissions: https://github.com/rhythmagency/formulate/releases/tag/v0.6.0

The release notes here indicate how to export to CSV: https://github.com/rhythmagency/formulate/releases/tag/v0.6.3

For future reference, it is better to ask questions in the forum (the issue tracker is more for bugs and feature requests): https://our.umbraco.org/projects/backoffice-extensions/formulate/

**Comment by biapar** [comment]
Yes. I already see that handler, but have you an example on how to retrieve data in a razor view?

Saluti
ing. Biagio Paruolo

**Comment by Nicholas-Westby** [comment]
Take a look at this function, `GenerateCsvOfFormSubmissions `: https://github.com/rhythmagency/formulate/blob/69cec9a739158d11a6eff0526a11a9830df060f5/src/formulate.app/Controllers/StoredDataDownloadController.cs#L155-L264

That is how the export to CSV function extracts the form submissions from the database. You could do something similar. Here's the main part you're likely to be interested in:

```cs
// Query database for form submissions.
var query = new Sql().Select("*").From("FormulateSubmission")
    .Where("FormId = @0", formId).OrderByDescending("CreationDate");
var entries = db.Fetch<FormulateSubmission>(query).ToList();

// Extract field values from the database entries.
foreach (var entry in entries)
{
    var extractedRow = new Dictionary<Guid, string>();
    var exportRow = new SubmissionExport()
    {
        Submission = entry,
        Values = extractedRow
    };
    extractedValues.Add(exportRow);
    var values = GetValuesForFields(entry.DataValues);
    var filenames = GetValuesForFiles(entry.FileValues);
    foreach (var fieldId in fieldIds)
    {
        var value = default(string);
        if (values.TryGetValue(fieldId, out value))
        {
        }
        else if (filenames.TryGetValue(fieldId, out value))
        {
        }
        else
        {
            value = null;
        }
        extractedRow[fieldId] = value;
    }
}
```
