### ISSUE TITLE
Change Mouse Pointer on Hover of Expand/Delete Icons

### ISSUE THREAD

**Issue by Nicholas-Westby** [rhythmagency/formulate#80]
This applies to both the form fields and the form handlers. Take this example:

![field](https://cloud.githubusercontent.com/assets/5933222/22380925/405b9bfa-e474-11e6-8d0d-408bd8aabed7.png)

Both of those icons should have a mouse pointer on hover that indicates they are clickable. Related discussion: https://github.com/rhythmagency/formulate/issues/77

**Comment by FuelAgency** [comment]
Think I just went about it entirely incorrectly (I'm new to Git) but I've fixed some UX styles for Formulate. I forked, cloned, committed then pushed to https://github.com/FuelAgency/formulate.

Changed: 

FORMS
- **Add / Plus** cursor: pointer
- **X / Delete** cursor: pointer
- **Move / Re-Order** cursor: move

LAYOUTS
- **Click to Add Row** text-decoration:underline
- **Layout field organisation** cursor: move

Can you merge this somehow?

**Comment by Nicholas-Westby** [comment]
Thanks for this. Happy to merge most of it in. Don't think I'm a fan of underlining the text in the "Click to Add Row" (it is already a button that says to click it, so an underline feels redundant).

In order for me to merge this in, you should submit a pull request. A "pull request" is essentially you initiating a request for me to pull your changes into the main repository. It looks like you've already forked the repo, so that's the first step. Next, GitHub should show a "Create Pull Request" (or similar) button. Click that and follow the instructions. I believe it allows you to choose the destination branch. Choose "develop".

Here's a short guide: https://help.github.com/articles/creating-a-pull-request/

**Comment by Nicholas-Westby** [comment]
This has been merged into the develop branch via this pull request: https://github.com/rhythmagency/formulate/pull/98
