### ISSUE TITLE
Default value for fields: static and dynamic

### ISSUE THREAD

**Issue by biapar** [rhythmagency/formulate#81]
How to assign a default value ( static or dynamic ) for fields? For example: in a field we need save the login username.

**Comment by Nicholas-Westby** [comment]
Happy to look into this for you, but would you mind asking this in the forum?: https://our.umbraco.org/projects/backoffice-extensions/formulate/formulate-questions/

The issue tracker is more for bug reports and feature requests. The forum is a better place to ask questions (others familiar with Formulate may be able to answer before I can get to it). Thanks!
