### ISSUE TITLE
Suggestion - RTE field

### ISSUE THREAD

**Issue by alecrt** [rhythmagency/formulate#9]
Hi man,

you form editor is as simple as powerfull. That's a great great job!

The only thing i found missing is a Rich Text Editor Field to better style the header of the form. 
Are you planning to support it?

Thanks again for you work,
Alessandro

**Comment by Nicholas-Westby** [comment]
I don't understand what you mean. Could you go into some more detail?

**Comment by Nicholas-Westby** [comment]
Haven't heard a response in about a month, so i'm closing this ticket.
