### ISSUE TITLE
Prefix attributes with data- for valid html

### ISSUE THREAD

**Issue by LeaTark** [rhythmagency/formulate#94]
Some attributes aren't prefixed data- so don't pass wc3 html validation.

![validate](https://cloud.githubusercontent.com/assets/25925693/23178754/7f208a1e-f863-11e6-8f46-b5f5af724299.gif)

**Comment by Nicholas-Westby** [comment]
This issue is a few years old and seems to refer to the AngularJS template (rather than the plain JavaScript version), so I'll close this out. We can open a new ticket if somebody is interested in tackling any issues there may be with the plain JavaScript template.
